name: Deploy to Google Play

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Use pnpm ðŸ—œï¸
        uses: pnpm/action-setup@v2
        with:
          version: 10.17.0
          run_install: false

      - name: Use Node ðŸ¢
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'

      - name: Install dependencies âš™ï¸
        run: pnpm install --frozen-lockfile

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Set up JDK â˜•
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.keystore
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

      - name: Set Gradle signing env
        run: |
          echo "RELEASE_KEYSTORE=$GITHUB_WORKSPACE/android/app/my-release-key.keystore" >> $GITHUB_ENV
          echo "RELEASE_KEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Release AAB
        run: |
          cd android
          ./gradlew clean bundleRelease

      - name: Upload to Google Play (internal track)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: dev.erian.coffeepass
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft